FROM ubi8

EXPOSE 8001

# Set Vars
ARG DIR=/root

WORKDIR ${DIR}  
# Install Python
RUN dnf -y install python3.11 git make &&\
    /usr/bin/git clone https://github.com/zylon-ai/private-gpt 

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
ENV PATH=${PATH}:/bin:${DIR}/.local:${DIR}/.local/bin:${DIR}/.cache/pypoetry/virtualenvs

WORKDIR ${DIR}/private-gpt

RUN python3.11 -m venv . &&\
    chmod +x bin/activate &&\
    ./bin/activate

# setup poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
# poetry install 
RUN ~/.local/bin/poetry install --extras "ui llms-ollama embeddings-ollama vector-stores-qdrant"
# Use sed to replace model calls in setting*.yaml files
ENV PGPT_PROFILES="ollama"

# # Setup entrypoint operations with entrypoint.sh
COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT [ "bash", "-c", "/entrypoint.sh" ]