FROM ubi8

# Ports to expose during RUNTIME
EXPOSE 11434

# Set Vars
ARG DIR=/root
ARG OLLAMA_URL=https://ollama.com/download/ollama-linux-amd64.tgz
ARG OLLAMA_DEST=ollama-linux-amd64.tgz

WORKDIR ${DIR}  
# Install ollama
RUN curl -L ${OLLAMA_URL} -o ${OLLAMA_DEST} &&\
    tar -C /usr -xzf ${OLLAMA_DEST} &&\
    rm -f ${OLLAMA_DEST}
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV PATH=$PATH:/root/.local:/root/.local/bin

ENTRYPOINT [ "ollama", "serve" ] 
